server:
  port: 8080
  servlet:
    context-path: /foxbase-be

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foxbase_db
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

